name: CI / pytest + coverage + PR comment

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  test-and-comment:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout exactly the PR’s HEAD (not the base branch)
      - name: Checkout PR’s HEAD
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      # 2) Install Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3) Install your runtime + test deps (including colorama)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov colorama

      # 4) Run pytest + coverage, capture its entire output into a step-output
      - name: Run pytest + coverage and capture output
        id: run-tests
        run: |
          # Run pytest (with term-missing coverage) and redirect all stdout/stderr:
          pytest --cov=./ --cov-report=term-missing > pytest_output.txt 2>&1 || true

          # Expose the full contents of pytest_output.txt as a multiline output called "report"
          echo "report<<EOF" >> "$GITHUB_OUTPUT"
          cat pytest_output.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      # 5) If tests passed, add the “Ready for Review” label
      - name: Add “Ready for Review” label
        if: ${{ steps.run-tests.outcome == 'success' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            Ready for Review

      # 6) Always (success or failure) post a comment containing the pytest + coverage text
      - name: Comment test & coverage results on PR
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Wrap the captured output in triple backticks for readability
            const reportBlock = `\`\`\`\n${{ steps.run-tests.outputs.report }}\n\`\`\``

            const body = [
              "### 🧪 Pytest + Coverage Results",
              "",
              reportBlock
            ].join("\n")

            // Create a comment on the PR (issue_number = PR number)
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            })
